"""Momentum Sniper V22 runtime patch fragment."""
PATCH_SOURCE = r'''
def pull_ranked_creators(preset, count):
    """Get top N creators from the JSON response generated by a saved Creator filter."""
    click_js = _saved_filter_click_js(preset)
    acts = login_actions() + [
        {"type": "executeJavascript", "script": "location.assign('https://www.kalodata.com/creator')"},
        {"type": "wait", "milliseconds": 15000},
        {"type": "executeJavascript", "script": CREATOR_NETWORK_CAPTURE_JS},
        {"type": "executeJavascript", "script": click_js},
        {"type": "wait", "milliseconds": 8000},
        {"type": "executeJavascript", "script": CREATOR_NETWORK_CAPTURE_READ_JS},
    ]
    vals = fc(acts, f"creator-json:{preset}")

    for v in vals:
        if isinstance(v, str) and v.startswith(("preset-", "creator-json-")):
            log(f"  Creator JSON: {v}")

    capture_wrap = _browser_result(vals, "creator_capture") or {}
    capture = capture_wrap.get("creator_capture") or {}
    hits = capture.get("hits") or []

    # Use the newest successful creator/queryList response generated by the custom filter.
    response = None
    request_body = None
    for hit in reversed(hits):
        if isinstance(hit, dict) and int(hit.get("status") or 0) in (200, 201):
            if hit.get("data") is not None:
                response = hit.get("data")
                request_body = hit.get("body")
                break

    if response is None:
        raise RuntimeError(
            f"Saved Creator filter {preset!r} clicked, but no /creator/queryList JSON response "
            "was captured. This is now a network-capture failure, not a table-row failure."
        )

    rows = _deep_records(response, "creator")
    if not rows:
        raise RuntimeError(
            f"Kalodata returned /creator/queryList JSON for {preset!r}, but no creator records "
            "could be identified in the payload."
        )

    targets = []
    seen = set()
    for rank, row in enumerate(rows[:count], start=1):
        target = _creator_from_json(row, rank=rank)
        dedupe = target["creator_id"] or target["handle"].lower() or target["name"].lower()
        if not dedupe or dedupe in seen:
            continue
        seen.add(dedupe)
        targets.append(target)
        log(
            f"  selected #{rank}: "
            f"{target.get('handle') or target.get('name') or target.get('creator_id')} "
            f"| JSON"
        )

    if not targets:
        raise RuntimeError(
            f"/creator/queryList returned {len(rows)} records, but none had a usable creator ID/handle."
        )

    log(f"  captured {len(rows)} ranked creators from Kalodata JSON; using top {len(targets)}")
    return targets

def find_creator_by_name(query):
    """Resolve a creator using Kalodata's own authenticated full-text JSON endpoint."""
    raw_q = str(query or "").strip()
    if not raw_q:
        raise RuntimeError("Enter a creator name or @handle.")
    search_q = raw_q[1:] if raw_q.startswith("@") else raw_q

    body = {
        "country_code": "us",
        "keyword": search_q,
        "scope": [{"index": "creator", "pageNo": 1, "pageSize": 20}],
    }
    key = "__momentumCreatorSearch"
    marker = "creator_search"
    acts = login_actions() + [
        {"type": "executeJavascript", "script": "location.assign('https://www.kalodata.com/creator')"},
        {"type": "wait", "milliseconds": 5000},
        {"type": "executeJavascript", "script": _start_internal_fetch_js(key, "/overview/fullText/search", body)},
        {"type": "wait", "milliseconds": 4500},
        {"type": "executeJavascript", "script": _read_internal_fetch_js(key, marker)},
    ]
    vals = fc(acts, f"creator-search-json:{raw_q}")
    wrap = _browser_result(vals, marker) or {}
    result = wrap.get(marker) or {}

    if int(result.get("status") or 0) != 200 or result.get("json") is None:
        raise RuntimeError(
            f"Kalodata internal creator search failed for {raw_q!r}: "
            f"HTTP {result.get('status') or 0} {result.get('error') or result.get('text') or ''}".strip()
        )

    rows = _deep_records(result.get("json"), "creator")
    if not rows:
        raise RuntimeError(f"Kalodata returned no creator JSON records for {raw_q!r}.")

    want = re.sub(r"[^a-z0-9._-]+", "", search_q.lower())

    def score(row):
        target = _creator_from_json(row)
        h = re.sub(r"[^a-z0-9._-]+", "", target["handle"].lower().lstrip("@"))
        n = re.sub(r"[^a-z0-9]+", "", target["name"].lower())
        wn = re.sub(r"[^a-z0-9]+", "", search_q.lower())
        if h and h == want:
            return 100
        if n and n == wn:
            return 95
        if h and (h.startswith(want) or want.startswith(h)):
            return 80
        if want and (want in h or wn in n):
            return 60
        return 0

    rows.sort(key=score, reverse=True)
    target = _creator_from_json(rows[0])

    if not target.get("creator_id"):
        raise RuntimeError(
            f"Kalodata found {target.get('handle') or target.get('name') or raw_q}, "
            "but the internal search payload did not include a creator UID."
        )

    if raw_q.startswith("@") and target.get("handle"):
        got = re.sub(r"[^a-z0-9._-]+", "", target["handle"].lower().lstrip("@"))
        if want and got and got != want:
            raise RuntimeError(
                f"Kalodata resolved {raw_q} to {target['handle']}; stopping rather than scanning the wrong creator."
            )

    log(
        f"  Creator JSON search -> "
        f"{target.get('handle') or target.get('name')} [{target.get('creator_id')}]"
    )
    return target

def pull_top_creator_products(creator):
    """Pull a creator's top products from Kalodata's authenticated internal JSON endpoint."""
    cid = str(creator.get("creator_id") or "").strip()
    if not cid:
        raise RuntimeError(
            f"Creator {creator.get('handle') or creator.get('name') or ''} has no Kalodata creator ID."
        )

    end = datetime.date.today() - datetime.timedelta(days=1)
    start = end - datetime.timedelta(days=29)
    body = {
        "id": cid,
        "startDate": str(start),
        "endDate": str(end),
        "cateIds": [],
        "sellerId": "",
        "authority": True,
        "pageNo": 1,
        "pageSize": 10,
        "sort": [{"field": "revenue", "type": "DESC"}],
    }
    key = f"__momentumCreatorProducts_{re.sub(r'[^A-Za-z0-9_]', '_', cid)}"
    marker = "creator_products"

    acts = login_actions() + [
        {"type": "executeJavascript", "script": "location.assign('https://www.kalodata.com/creator')"},
        {"type": "wait", "milliseconds": 4000},
        {"type": "executeJavascript", "script": _start_internal_fetch_js(key, "/creator/detail/searchProducts", body)},
        {"type": "wait", "milliseconds": 5500},
        {"type": "executeJavascript", "script": _read_internal_fetch_js(key, marker)},
    ]
    vals = fc(acts, f"creator-products-json:{creator.get('handle') or cid}")
    wrap = _browser_result(vals, marker) or {}
    result = wrap.get(marker) or {}

    if int(result.get("status") or 0) != 200 or result.get("json") is None:
        raise RuntimeError(
            f"Kalodata creator product JSON failed for "
            f"{creator.get('handle') or creator.get('name') or cid}: "
            f"HTTP {result.get('status') or 0} {result.get('error') or result.get('text') or ''}".strip()
        )

    rows = _deep_records(result.get("json"), "product")
    products = []
    seen = set()
    for row in rows:
        p = _product_from_json(row, creator)
        if not p["id"] or p["id"] in seen:
            continue
        seen.add(p["id"])
        products.append(p)
        if len(products) >= 10:
            break

    if not products:
        raise RuntimeError(
            f"Kalodata returned creator product JSON for "
            f"{creator.get('handle') or creator.get('name') or cid}, but no product IDs were found."
        )

    log(
        f"  Creator JSON products -> {len(products)} products for "
        f"{creator.get('handle') or creator.get('name') or cid}"
    )
    return products
'''

def install(legacy):
    exec(PATCH_SOURCE, legacy.__dict__)
